name: Trivy image scan, submit result to GHAS
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      team:
        required: true
        type: string
      upload-sarif:
        required: false
        type: boolean
        default: true
      severities:
        required: false
        description: 'Define severity levels we care about. Ex: MEDIUM,HIGH,CRITICAL'
        type: string
        default: 'HIGH,CRITICAL'
jobs:
  scan-and-submit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to write sarif
      security-events: write # push sarif to github security
      id-token: write # for nais/login
      actions: read # for private repositories
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4.1.1
      - uses: nais/login@557ec71a21c53ce9a8f672e1889997d2d564bd8c # ratchet:nais/login@v0
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: ${{ inputs.team }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@84384bd6e777ef152729993b8145ea352e9dd3ef # ratchet:aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.image }}'
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true
      - name: Upload results to GitHub Security
        if: inputs.upload-sarif
        uses: github/codeql-action/upload-sarif@e8893c57a1f3a2b659b6b55564fdfdbbd2982911 # ratchet:github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy.sarif'
